// Hmm... don't quite get the intuition here.
// We need to ensure that ALL descendents of "right" are greater than "val".
// And same for left and less than...
// Somewhat similar to Balanced tree it feels like, where we have to keep track of height as we dfs...
