// Huh... another "hard".... doesn't seem that hard... maybe deceptive....

// Given array like ratings like [1,0,2], find the minimum number of candies you must give.
// Each kid must get 1. And if a kid has a higher rating than their neighbor, they must get more candies.

// It seems like we can just walk through...
// Init with all 1s.
// Then walk through and if we see a higher rating, we increment the candy count.
// Then we walk back and if we see a higher rating, we increment the candy count.
// We take the max of the two counts at each step.

// Ok maybe that would work...

// MY IDEA was...
// Walk through... init with 1s... and if we are higher rating than left neighbor, and must increment, then do so...
// But if we are lower than left neighbor... we must incremenet count of all left neighbors by 1. Right? Well...just until we reach a peak...
